### ISSUE TITLE
Error during read-in

### ISSUE THREAD

**Issue by royfrancis** [hartleys/QoRTs#16]
With version 1.1.2, I get this error when reading in data

```
decoder.raw <- data.frame(unique.ID = names, qc.data.dir = paths)
decoder <- completeAndCheckDecoder(decoder = decoder.raw)
qortsdata <- read.qc.results.data("", decoder = decoder, calc.DESeq2 = TRUE, calc.edgeR = TRUE)

reading QC.summary.txt files...
Error in read.in.scalaQC.files(infile.dir, lanebam.list, qc.data.dir.list,  : 
  File not found: NA()
```

**Comment by royfrancis** [comment]
Ok. a few of the directories had no qorts qc output. They failed during run time. Looking at the run log, I see (only showing end of log file):

```
QC Utilities Generated!
[Time: 2016-06-08 00:56:43] [Mem usage: [2415MB / 5GB]] [Elapsed Time: 00:03:35.0689]
..........[1000000 Read-Pairs processed] [Time: 2016-06-08 01:02:14]
..........[2000000 Read-Pairs processed] [Time: 2016-06-08 01:07:00]
..........[3000000 Read-Pairs processed] [Time: 2016-06-08 01:11:18]
..........[4000000 Read-Pairs processed] [Time: 2016-06-08 01:15:40]
.......
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
          java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" net.sf.samtools.FileTruncatedException: Premature end of file
        at net.sf.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:382)
        at net.sf.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:127)
        at net.sf.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:252)
        at java.io.DataInputStream.read(DataInputStream.java:149)
        at net.sf.samtools.util.BinaryCodec.readBytesOrFewer(BinaryCodec.java:395)
        at net.sf.samtools.util.BinaryCodec.readBytes(BinaryCodec.java:371)
        at net.sf.samtools.util.BinaryCodec.readByteBuffer(BinaryCodec.java:481)
        at net.sf.samtools.util.BinaryCodec.readInt(BinaryCodec.java:492)
        at net.sf.samtools.BAMRecordCodec.decode(BAMRecordCodec.java:178)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.getNextRecord(BAMFileReader.java:650)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.advance(BAMFileReader.java:624)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:618)
        at net.sf.samtools.BAMFileReader$BAMFileIterator.next(BAMFileReader.java:588)
        at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:774)
        at net.sf.samtools.SAMFileReader$AssertableIterator.next(SAMFileReader.java:752)
        at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
        at scala.collection.Iterator$GroupedIterator.takeDestructively(Iterator.scala:930)
        at scala.collection.Iterator$GroupedIterator.go(Iterator.scala:945)
        at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:985)
        at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:988)
        at internalUtils.stdUtils$$anon$1.hasNext(stdUtils.scala:179)
        at scala.collection.Iterator$JoinIterator.hasNext(Iterator.scala:193)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:406)
        at internalUtils.commonSeqUtils$$anon$2.hasNext(commonSeqUtils.scala:704)
        at internalUtils.stdUtils$IteratorProgressReporter$$anon$4.hasNext(stdUtils.scala:298)
        at scala.collection.Iterator$class.foreach(Iterator.scala:743)
        at internalUtils.stdUtils$IteratorProgressReporter$$anon$4.foreach(stdUtils.scala:296)
        at qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1055)
        at qcUtils.runAllQC$.run(runAllQC.scala:774)
        at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:502)
        at runner.runner$.main(runner.scala:92)
        at runner.runner.main(runner.scala)
```

**Comment by hartleys** [comment]
It looks like samtools is complaining that the bam file is truncated. Maybe they were cut off in a file transfer at some point?

Is this human data? How large are the bam files? Have you successfully opened them with any other tools?

**Comment by royfrancis** [comment]
yes. they were truncated bam files. They also wouldn't open in igv.
