### ISSUE TITLE
merge(all)counts failing to create directories

### ISSUE THREAD

**Issue by davemcg** [hartleys/QoRTs#19]
QoRTs 1.1.6 on biowulf2.nih.gov
decoder file
```
[mcgaugheyd@cn2673 nlz2_rna-seq]$ cat decoder.txt 
sample.ID lane.ID unique.ID qc.data.dir group.ID input.read.pair.count
Het-1 Seven 160121_OPTIMUS_C7NWYANXX.7.11716124 160121_OPTIMUS_C7NWYANXX.7.11716124.Aligned.sortedByCoord.out Het 30051866
Het-2 Seven 160121_OPTIMUS_C7NWYANXX.7.11716125 160121_OPTIMUS_C7NWYANXX.7.11716125.Aligned.sortedByCoord.out Het 31560923
Hom-2 Seven 160121_OPTIMUS_C7NWYANXX.7.11716126 160121_OPTIMUS_C7NWYANXX.7.11716126.Aligned.sortedByCoord.out Hom 30489682
Hom-1 Seven 160121_OPTIMUS_C7NWYANXX.7.11716127 160121_OPTIMUS_C7NWYANXX.7.11716127.Aligned.sortedByCoord.out Hom 25491149
WT-1 Seven 160121_OPTIMUS_C7NWYANXX.7.11716128 160121_OPTIMUS_C7NWYANXX.7.11716128.Aligned.sortedByCoord.out WT 33500427
Hom-3 Seven 160121_OPTIMUS_C7NWYANXX.7.11716129 160121_OPTIMUS_C7NWYANXX.7.11716129.Aligned.sortedByCoord.out Hom 31181930
WT-3 Seven 160121_OPTIMUS_C7NWYANXX.7.11716130 160121_OPTIMUS_C7NWYANXX.7.11716130.Aligned.sortedByCoord.out WT 33223515
WT-2 Seven 160121_OPTIMUS_C7NWYANXX.7.11716131 160121_OPTIMUS_C7NWYANXX.7.11716131.Aligned.sortedByCoord.out WT 31167919
Het-3 Seven 160121_OPTIMUS_C7NWYANXX.7.11716132 160121_OPTIMUS_C7NWYANXX.7.11716132.Aligned.sortedByCoord.out Het 31923255
Het-1 Eight 160121_OPTIMUS_C7NWYANXX.8.11716124 160121_OPTIMUS_C7NWYANXX.8.11716124.Aligned.sortedByCoord.out Het 28616822
Het-2 Eight 160121_OPTIMUS_C7NWYANXX.8.11716125 160121_OPTIMUS_C7NWYANXX.8.11716125.Aligned.sortedByCoord.out Het 30014811
Hom-2 Eight 160121_OPTIMUS_C7NWYANXX.8.11716126 160121_OPTIMUS_C7NWYANXX.8.11716126.Aligned.sortedByCoord.out Hom 28987256
Hom-1 Eight 160121_OPTIMUS_C7NWYANXX.8.11716127 160121_OPTIMUS_C7NWYANXX.8.11716127.Aligned.sortedByCoord.out Hom 24322137
WT-1 Eight 160121_OPTIMUS_C7NWYANXX.8.11716128 160121_OPTIMUS_C7NWYANXX.8.11716128.Aligned.sortedByCoord.out WT 31843733
Hom-3 Eight 160121_OPTIMUS_C7NWYANXX.8.11716129 160121_OPTIMUS_C7NWYANXX.8.11716129.Aligned.sortedByCoord.out Hom 29651595
WT-3 Eight 160121_OPTIMUS_C7NWYANXX.8.11716130 160121_OPTIMUS_C7NWYANXX.8.11716130.Aligned.sortedByCoord.out WT 31596017
WT-2 Eight 160121_OPTIMUS_C7NWYANXX.8.11716131 160121_OPTIMUS_C7NWYANXX.8.11716131.Aligned.sortedByCoord.out WT 29607732
Het-3 Eight 160121_OPTIMUS_C7NWYANXX.8.11716132 160121_OPTIMUS_C7NWYANXX.8.11716132.Aligned.sortedByCoord.out Het 30373467
```

qorts technical replicates (output from qc)
```
[mcgaugheyd@cn2673 nlz2_rna-seq]$ ls qorts/
160121_OPTIMUS_C7NWYANXX.7.11716124.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.7.11716129.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716125.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716130.Aligned.sortedByCoord.out
160121_OPTIMUS_C7NWYANXX.7.11716125.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.7.11716130.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716126.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716131.Aligned.sortedByCoord.out
160121_OPTIMUS_C7NWYANXX.7.11716126.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.7.11716131.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716127.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716132.Aligned.sortedByCoord.out
160121_OPTIMUS_C7NWYANXX.7.11716127.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.7.11716132.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716128.Aligned.sortedByCoord.out
160121_OPTIMUS_C7NWYANXX.7.11716128.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716124.Aligned.sortedByCoord.out  160121_OPTIMUS_C7NWYANXX.8.11716129.Aligned.sortedByCoord.out
```

Look into one of the folders
```
[mcgaugheyd@cn2673 160121_OPTIMUS_C7NWYANXX.7.11716124.Aligned.sortedByCoord.out]$ ls
QC.biotypeCounts.txt.gz                       QC.gc.byRead.txt.gz                             QC.geneCounts.formatted.for.DESeq.txt.gz  QC.NVC.minus.clipping.R1.txt.gz  QC.quals.r2.txt.gz
QC.chromCount.txt.gz                          QC.gc.byRead.vsBaseCt.txt.gz                    QC.geneCounts.txt.gz                      QC.NVC.minus.clipping.R2.txt.gz  QC.spliceJunctionAndExonCounts.forJunctionSeq.txt.gz
QC.cigarOpDistribution.byReadCycle.R1.txt.gz  QC.gc.R1.txt.gz                                 QC.insert.size.debug.dropped.txt.gz       QC.NVC.raw.R1.txt.gz             QC.spliceJunctionCounts.knownSplices.txt.gz
QC.cigarOpDistribution.byReadCycle.R2.txt.gz  QC.gc.R2.txt.gz                                 QC.insert.size.debug.txt.gz               QC.NVC.raw.R2.txt.gz             QC.spliceJunctionCounts.novelSplices.txt.gz
QC.cigarOpLengths.byOp.R1.txt.gz              QC.geneBodyCoverage.byExpr.avgPct.txt.gz        QC.insert.size.txt.gz                     QC.NVC.tail.clip.R1.txt.gz       QC.summary.txt
QC.cigarOpLengths.byOp.R2.txt.gz              QC.geneBodyCoverage.by.expression.level.txt.gz  QC.N809Uh5DoVGx.log                       QC.NVC.tail.clip.R2.txt.gz
QC.exonCounts.formatted.for.DEXSeq.txt.gz     QC.geneBodyCoverage.DEBUG.intervals.txt.gz      QC.NVC.lead.clip.R1.txt.gz                QC.QORTS_COMPLETED_OK
QC.gc.byPair.txt.gz                           QC.geneBodyCoverage.genewise.txt.gz             QC.NVC.lead.clip.R2.txt.gz                QC.quals.r1.txt.gz
``` 
Failed mergeAllCounts (mergeCounts also fails)
```
[mcgaugheyd@cn2673 nlz2_rna-seq]$ java -Xmx20G -jar $QORTS_JARFILE mergeAllCounts qorts/ decoder.txt /data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/
Starting QoRTs v1.1.6 (Compiled Tue Jun 14 15:00:22 EDT 2016)
Starting time: (Tue Aug 02 09:32:12 EDT 2016)
INPUT_COMMAND(mergeAllCounts)
  INPUT_ARG(infileDir)=qorts/
  INPUT_ARG(decoderFile)=decoder.txt
  INPUT_ARG(outfile)=/data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/
Creating Directory: /data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/Hom-3
Successfully Created Directory: /data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/Hom-3
Merging DESeq data...
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
          java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.io.FileNotFoundException: /data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/Hom-3/QC.geneCounts.formatted.for.DESeq.txt.gz (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:206)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:156)
	at internalUtils.fileUtils$.openGzipWriter(fileUtils.scala:37)
	at internalUtils.fileUtils$.openWriterSmart(fileUtils.scala:51)
	at fileConversionUtils.mergeQcOutput$.mergeSimpleData(mergeQcOutput.scala:470)
	at fileConversionUtils.mergeQcOutput$.merge(mergeQcOutput.scala:258)
	at fileConversionUtils.mergeQcOutput$$anonfun$multirun$2.apply(mergeQcOutput.scala:180)
	at fileConversionUtils.mergeQcOutput$$anonfun$multirun$2.apply(mergeQcOutput.scala:179)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at fileConversionUtils.mergeQcOutput$.multirun(mergeQcOutput.scala:179)
	at fileConversionUtils.mergeQcOutput$multiMerger.run(mergeQcOutput.scala:159)
	at runner.runner$.main(runner.scala:92)
	at runner.runner.main(runner.scala)
```

The folders aren't being created.
```
[mcgaugheyd@cn2673 nlz2_rna-seq]$ cd /data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/Hom-3
bash: cd: /data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/Hom-3: No such file or directory
```

**Comment by davemcg** [comment]
Same issue happening on my mac with 1.1.8

**Comment by hartleys** [comment]
Hmm. Does the folder "/data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/" exist?

I'll do some testing tomorrow.

Sorry I've been so slow in responding, I've been away on vacation.

**Comment by davemcg** [comment]
Folder doesn't exist.

**Comment by hartleys** [comment]
The top-level directory must already exist. Otherwise when QoRTs attempts to create subdirectories it will silently fail.

So first create the directory using a command like:
mkdir /data/mcgaugheyd/projects/nei/brooks/nlz2_rna-seq/qorts/merge_cts/

Then run QoRTs.
