### ISSUE TITLE
ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by gonzalpk** [hartleys/QoRTs#24]
Hi,
I am trying to run QC on a 126bp single end reads aligned to the hg19 genome with Tophat2. I get the error message: _Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1_
after the "Beginning allocation of genomic window array..." step. I am not how to resolve this error and in all honesty- where to start troubleshooting. I have pasted my commands and the error message I received below. I would greatly appreciate if you could shed some light on the error.
Thank you, 
Patrick.

**java -Xmx16000M -jar /projects/gonzalpk/QoRTs-master/QoRTs_1.1.8/QoRTs.jar QC \
--stranded --singleEnded --minMAPQ 50 \
--chromSizes /DownSyndrome/hg19_chromsizes.txt \
/newAlignments/C2_2_1_top2aligned.bam \
/DownSyndrome/genes.gtf \
/newAlignments/C2_2_1_top2aligned**

Creating Directory: /lustre/janus_scratch/gonzalpk/DownSyndrome/newAlignments/C2_2_1_top2aligned**

Created Log File: /lustre/janus_scratch/gonzalpk/DownSyndrome/newAlignments/C2_2_1_top2aligned/QC.M3LgPfYRQzSx.log
Starting QC
[Time: 2016-09-26 11:04:07] [Mem usage: [19MB / 380MB]] [Elapsed Time: 00:00:00.0000]
QoRTs is Running in single-end mode.
Note: read-sorting is irrelevant in single-ended mode.
Running functions: NVC, GCDistribution, GeneCalcs, QualityScoreDistribution, 
        writeJunctionSeqCounts, writeKnownSplices, 
        writeNovelSplices, writeClippedNVC, CigarOpDistribution, 
        chromCounts, writeSpliceExon, writeGenewiseGeneBody, 
        JunctionCalcs, writeGeneCounts, writeBiotypeCounts, 
        writeDESeq, writeDEXSeq, makeWiggles, writeGeneBody, 
        StrandCheck
Pre-alignment read count unknown (Set --seqReadCt or --rawfastq)
Checking first 10000 reads. Checking SAM file for formatting errors...
   Note: Detected TopHat Alignment Program.
         Version: "2.1.1"
   IMPORTANT NOTE: Detected TopHat Alignment Program, version > 2. 
       TopHat v2+ uses a different MAPQ convention than most aligners. 
       Make sure you set the --minMAPQ parameter to 50 if you want to ignore 
       multi-mapped reads.
Done checking first 10000 reads. No major problems detected.
SAMRecord Reader Generated. Read length: 126.
[Time: 2016-09-26 11:04:09] [Mem usage: [82MB / 675MB]] [Elapsed Time: 00:00:01.0986]
Compiling flat feature annotation, internally in memory...
Internal flat feature annotation compiled!
Beginning allocation of genomic window array...
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
          java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at fileConversionUtils.bamToWiggle$$anonfun$genChrom$1.apply(bamToWiggle.scala:616)
        at fileConversionUtils.bamToWiggle$$anonfun$genChrom$1.apply(bamToWiggle.scala:613)
        at scala.collection.Iterator$class.foreach(Iterator.scala:743)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
        at fileConversionUtils.bamToWiggle$.genChrom(bamToWiggle.scala:613)
        at fileConversionUtils.bamToWiggle$QcBamToWig.<init>(bamToWiggle.scala:460)
        at qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1016)
        at qcUtils.runAllQC$.run(runAllQC.scala:774)
        at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:502)
        at runner.runner$.main(runner.scala:92)
        at runner.runner.main(runner.scala)
(END)

**Comment by gonzalpk** [comment]
My apologies...After checking all the input files I noticed that the chromSizes file from UCSC included "chr" for the chromosome names while the fasta file and gtf file do not. I simply removed the chr from the chromSizes file and it is running fine now.
