### ISSUE TITLE
Error at makeSpliceJunctionBed step

### ISSUE THREAD

**Issue by nimarafati** [hartleys/QoRTs#30]
Hi,

Thanks for developing such a very useful tool! I was using QoRTs successfully for few of my datasets but in one of them my run stuck at **makeSpliceJunctionBed** step. Here is the error I get:

"Writing Output...
Making '.bed' junction count tracks... 
Compiling flat feature annotation, internally in memory...
Internal flat feature annotation compiled!
> makeSpliceJunctionBed: initialized gff reader.
> makeSpliceJunctionBed: build splice junction map.
> makeSpliceJunctionBed: Finished setup.
> makeSpliceJunctionBed: opening file: "/pica/v8/b2017031_nobackup/private/UserDirectories/nima/tmpRabbit/Domestication/GSNAP/Sample_P1_W2-R7/Sample_P1_W2-R7_QC_Rabbit-Ensembl76-UCSC//QC.spliceJunctionAndExonCounts.forJunctionSeq.txt.gz"
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
          java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.io.FileNotFoundException: /pica/v8/b2017031_nobackup/private/UserDirectories/nima/tmpRabbit/Domestication/GSNAP/Sample_P1_W2-R7/Sample_P1_W2-R7_QC_Rabbit-Ensembl76-UCSC/QC.spliceJunctionAndExonCounts.forJunctionSeq.txt.gz (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at internalUtils.fileUtils$.getLinesSmartUnzip(fileUtils.scala:162)
	at fileConversionUtils.makeSpliceJunctionBed$$anonfun$13.apply(makeSpliceJunctionBed.scala:370)
	at fileConversionUtils.makeSpliceJunctionBed$$anonfun$13.apply(makeSpliceJunctionBed.scala:368)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at fileConversionUtils.makeSpliceJunctionBed$.run_helper(makeSpliceJunctionBed.scala:368)
	at fileConversionUtils.makeSpliceJunctionBed$.run(makeSpliceJunctionBed.scala:224)
	at qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1160)
	at qcUtils.runAllQC$.run(runAllQC.scala:749)
	at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:479)
	at runner.runner$.main(runner.scala:91)
	at runner.runner.main(runner.scala)"

Apparently it cannot write **QC.spliceJunctionAndExonCounts.forJunctionSeq.txt.gz** file or?

I will very appreciate if you can help me with this.

Best regards,
Nima

**Comment by hartleys** [comment]
My initial guess would be that the directory doesnt exist or doesnt have
write permission.

It looks like you're using linux (or possibly osx).

Try the following command:

ls -l /pica/v8/b2017031_nobackup/private/UserDirectories/nima/
tmpRabbit/Domestication/GSNAP/Sample_P1_W2-R7/Sample_P1_W2-
R7_QC_Rabbit-Ensembl76-UCSC




On Feb 20, 2017 5:20 AM, "nimarafati" <notifications@github.com> wrote:

Hi,

Thanks for developing such a very useful tool! I was using QoRTs
successfully for few of my datasets but in one of them my run stuck at
*makeSpliceJunctionBed* step. Here is the error I get:

"Writing Output...
Making '.bed' junction count tracks...
Compiling flat feature annotation, internally in memory...
Internal flat feature annotation compiled!

makeSpliceJunctionBed: initialized gff reader.
makeSpliceJunctionBed: build splice junction map.
makeSpliceJunctionBed: Finished setup.
makeSpliceJunctionBed: opening file: "/pica/v8/b2017031_nobackup/
private/UserDirectories/nima/tmpRabbit/Domestication/GSNAP/
Sample_P1_W2-R7/Sample_P1_W2-R7_QC_Rabbit-Ensembl76-UCSC//QC.
spliceJunctionAndExonCounts.forJunctionSeq.txt.gz"
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.io.FileNotFoundException:
/pica/v8/b2017031_nobackup/private/UserDirectories/nima/
tmpRabbit/Domestication/GSNAP/Sample_P1_W2-R7/Sample_P1_W2-
R7_QC_Rabbit-Ensembl76-UCSC/QC.spliceJunctionAndExonCounts.forJunctionSeq.txt.gz
(No such file or directory)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(FileInputStream.java:195)
at java.io.FileInputStream.(FileInputStream.java:138)
at java.io.FileInputStream.(FileInputStream.java:93)
at internalUtils.fileUtils$.getLinesSmartUnzip(fileUtils.scala:162)
at fileConversionUtils.makeSpliceJunctionBed$$anonfun$13.apply(
makeSpliceJunctionBed.scala:370)
at fileConversionUtils.makeSpliceJunctionBed$$anonfun$13.apply(
makeSpliceJunctionBed.scala:368)
at scala.collection.TraversableLike$$anonfun$map$
1.apply(TraversableLike.scala:245)
at scala.collection.TraversableLike$$anonfun$map$
1.apply(TraversableLike.scala:245)
at scala.collection.Iterator$class.foreach(Iterator.scala:743)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
at scala.collection.AbstractTraversable.map(Traversable.scala:104)
at fileConversionUtils.makeSpliceJunctionBed$.run_
helper(makeSpliceJunctionBed.scala:368)
at fileConversionUtils.makeSpliceJunctionBed$.run(
makeSpliceJunctionBed.scala:224)
at qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1160)
at qcUtils.runAllQC$.run(runAllQC.scala:749)
at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:479)
at runner.runner$.main(runner.scala:91)
at runner.runner.main(runner.scala)"

Apparently it cannot write
*QC.spliceJunctionAndExonCounts.forJunctionSeq.txt.gz* file or?

I will very appreciate if you can help me with this.

Best regards,
Nima

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hartleys/QoRTs/issues/30>, or mute the thread
