### ISSUE TITLE
FATAL_ERROR mergeWig QoRTs v1.2.26

### ISSUE THREAD

**Issue by semacu** [hartleys/QoRTs#33]
Dear Hartleys,

I am getting the following error when running mergeWig to output the mean between the three following .wig files. 

Do you know what the error message might be telling me? In fact, it creates the output .wig file but I am not sure if correct.

Thanks,
Sergio

- Command:
$java -Xmx2G -jar QoRTs.jar \
mergeWig \
--calcMean \
--filenames libA/pooled/libA.wig,libB/pooled/libB.wig,libC/pooled/libC.wig \
libA_libB_libC.wig

- Output:
Starting QoRTs v1.2.26 (Compiled Tue Mar  7 14:22:03 EST 2017)
Starting time: (Wed Mar 29 15:19:05 BST 2017)
INPUT_COMMAND(mergeWig)
  INPUT_ARG(outfile)=libA_libB_libC.wig
  INPUT_ARG(calcMean)=true
  INPUT_ARG(filenames)=Some(List(libA/pooled/libA.wig, libB/pooled/libB.wig, libC/pooled/libC.wig))
opening file: libA/pooled/libA.wig
        with adj factor 3.0
opening file: libB/pooled/libB.wig
        with adj factor 3.0
opening file: libC/pooled/libC.wig
        with adj factor 3.0

...
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
          java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.util.NoSuchElementException: next on empty iterator
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
	at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
	at scala.io.BufferedSource$BufferedLineIterator.next(BufferedSource.scala:81)
	at scala.io.BufferedSource$BufferedLineIterator.next(BufferedSource.scala:66)
	at fileConversionUtils.SumWigglesFast$$anon$3.next(SumWigglesFast.scala:351)
	at fileConversionUtils.SumWigglesFast$$anon$3.next(SumWigglesFast.scala:349)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:363)
	at scala.collection.Iterator$$anon$1.next(Iterator.scala:869)
	at scala.collection.Iterator$$anon$18.next(Iterator.scala:632)
	at fileConversionUtils.SumWigglesFast$$anon$1$$anonfun$next$1.apply(SumWigglesFast.scala:243)
	at fileConversionUtils.SumWigglesFast$$anon$1$$anonfun$next$1.apply(SumWigglesFast.scala:243)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:143)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:143)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:143)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at fileConversionUtils.SumWigglesFast$$anon$1.next(SumWigglesFast.scala:243)
	at fileConversionUtils.SumWigglesFast$$anon$1.next(SumWigglesFast.scala:238)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:363)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at fileConversionUtils.SumWigglesFast$.runHelper2(SumWigglesFast.scala:257)
	at fileConversionUtils.SumWigglesFast$.run(SumWigglesFast.scala:167)
	at fileConversionUtils.SumWigglesFast$SumWigglesFast_runner.run(SumWigglesFast.scala:115)
	at runner.runner$.main(runner.scala:97)
	at runner.runner.main(runner.scala)

**Comment by hartleys** [comment]
This can happen if the wiggle files are not all the same length. Have you
checked that?

You can check the number of lines in a file with the "wc -l" command.


On Mar 29, 2017 10:40 AM, "Sergio Martínez Cuesta" <notifications@github.com>
wrote:

Dear Hartleys,

I am getting the following error when running mergeWig to output the mean
between the three following .wig files.

Do you know what the error message might be telling me? In fact, it creates
the output .wig file but I am not sure if correct.

Thanks,
Sergio

   -

   Command:
   $java -Xmx2G -jar QoRTs.jar
   mergeWig
   --calcMean
   --filenames libA/pooled/libA.wig,libB/pooled/libB.wig,libC/pooled/libC.wig

   libA_libB_libC.wig
   -

   Output:
   Starting QoRTs v1.2.26 (Compiled Tue Mar 7 14:22:03 EST 2017)
   Starting time: (Wed Mar 29 15:19:05 BST 2017)
   INPUT_COMMAND(mergeWig)
   INPUT_ARG(outfile)=libA_libB_libC.wig
   INPUT_ARG(calcMean)=true
   INPUT_ARG(filenames)=Some(List(libA/pooled/libA.wig,
   libB/pooled/libB.wig, libC/pooled/libC.wig))
   opening file: libA/pooled/libA.wig
   with adj factor 3.0
   opening file: libB/pooled/libB.wig
   with adj factor 3.0
   opening file: libC/pooled/libC.wig
   with adj factor 3.0

...
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.util.NoSuchElementException: next on empty
iterator
at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
at scala.io.BufferedSource$BufferedLineIterator.next(
BufferedSource.scala:81)
at scala.io.BufferedSource$BufferedLineIterator.next(
BufferedSource.scala:66)
at fileConversionUtils.SumWigglesFast$$anon$3.next(SumWigglesFast.scala:351)
at fileConversionUtils.SumWigglesFast$$anon$3.next(SumWigglesFast.scala:349)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:363)
at scala.collection.Iterator$$anon$1.next(Iterator.scala:869)
at scala.collection.Iterator$$anon$18.next(Iterator.scala:632)
at fileConversionUtils.SumWigglesFast$$anon$1$$anonfun$next$1.apply(
SumWigglesFast.scala:243)
at fileConversionUtils.SumWigglesFast$$anon$1$$anonfun$next$1.apply(
SumWigglesFast.scala:243)
at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(
TraversableOnce.scala:143)
at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(
TraversableOnce.scala:143)
at scala.collection.Iterator$class.foreach(Iterator.scala:743)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.
scala:143)
at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
at fileConversionUtils.SumWigglesFast$$anon$1.next(SumWigglesFast.scala:243)
at fileConversionUtils.SumWigglesFast$$anon$1.next(SumWigglesFast.scala:238)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:363)
at scala.collection.Iterator$class.foreach(Iterator.scala:743)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
at fileConversionUtils.SumWigglesFast$.runHelper2(SumWigglesFast.scala:257)
at fileConversionUtils.SumWigglesFast$.run(SumWigglesFast.scala:167)
at fileConversionUtils.SumWigglesFast$SumWigglesFast_
runner.run(SumWigglesFast.scala:115)
at runner.runner$.main(runner.scala:97)
at runner.runner.main(runner.scala)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hartleys/QoRTs/issues/33>, or mute the thread

**Comment by semacu** [comment]
Thanks for letting me know, the files have different lenghts.

Best,
Sergio
