### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by chyr03** [hartleys/QoRTs#47]
Is my alignment file wrong?   QoRTs.jar was executed in windows platform. 

E:\junse>java -jar QoRTs.jar QC SAMP1.bam Bom7.gtf /output/
Starting QoRTs v1.2.42 (Compiled Fri Jun  2 12:23:55 EDT 2017)
Starting time: (Tue Oct 24 11:52:20 CST 2017)
INPUT_COMMAND(QC)
  INPUT_ARG(infile)=SAMP1.bam
  INPUT_ARG(gtffile)=Bom7.gtf
  INPUT_ARG(outdir)=/output/
Created Log File: /output//QC.2FZMQEgTctJt.log
Warning: run-in-progress file "/output//QC.QORTS_RUNNING" already exists. Is there another QoRTs job running?
NOTE: maximum allocation memory = 2.844786688 gigabytes.
    This might be ok, or might cause OutOfMemoryExceptions later.
    For most large datasets/genomes at least 4 gb is recommended.
    (Actual required memory may be less than this.)
    To increase the memory maximum, include the parameter -Xmx
    in between the java command and the -jar parameter.
    For example: to increase the memory maximum to 4 gigabytes:
        java -Xmx4G -jar /path/to/jar/QoRTs.jar QC ...
Starting QC
[Time: 2017-10-24 11:52:20] [Mem usage: [21MB / 192MB]] [Elapsed Time: 00:00:00.0000]
QoRTs is Running in paired-end mode.
QoRTs is Running in any-sorted mode.
NOTE: Function "overlapMatch" requires function "mismatchEngine". Adding "mismatchEngine" to the active function list...
Running functions: CigarOpDistribution, GCDistribution, GeneCalcs, InsertSize,
        JunctionCalcs, NVC, QualityScoreDistribution, StrandCheck,
        chromCounts, cigarLocusCounts, mismatchEngine, overlapMatch,
        readLengthDistro, writeBiotypeCounts, writeClippedNVC,
        writeDESeq, writeDEXSeq, writeGeneBody, writeGeneCounts,
        writeGenewiseGeneBody, writeJunctionSeqCounts,
        writeKnownSplices, writeNovelSplices, writeSpliceExon
Checking first 10000 reads. Checking SAM file for formatting errors...
   Sorting Note: Reads are not sorted by name (This is OK).
   Sorting Note: Reads are sorted by position (This is OK).
Done checking first 10000 reads. WARNINGS FOUND!
SAMRecord Reader Generated. Read length: 125.
[Time: 2017-10-24 11:52:22] [Mem usage: [405MB / 548MB]] [Elapsed Time: 00:00:02.0416]
Compiling flat feature annotation, internally in memory...
Internal flat feature annotation compiled!
QC Utilities Generated!
[Time: 2017-10-24 11:52:40] [Mem usage: [1048MB / 1303MB]] [Elapsed Time: 00:00:20.0131]
Finished reading SAM. Read: 345 reads/read-pairs.
Finished reading SAM. Used: 0 reads/read-pairs.
[Time: 2017-10-24 11:53:33] [Mem usage: [367MB / 1491MB]] [Elapsed Time: 00:01:13.0067]
> Read Stats:
>   READ_PAIR_OK                   0
>   TOTAL_READ_PAIRS               345
>   DROPPED_NOT_PROPER_PAIR        0
>   DROPPED_READ_FAILS_VENDOR_QC   0
>   DROPPED_MARKED_NOT_VALID       0
>   DROPPED_CHROMS_MISMATCH        0
>   DROPPED_PAIR_STRANDS_MISMATCH  0
>   DROPPED_IGNORED_CHROMOSOME     0
>   DROPPED_NOT_UNIQUE_ALIGNMENT   345
>   DROPPED_NO_ALN_BLOCKS   0
>   DROPPED_NOT_MARKED_RG   -1
Pre-alignment read count unknown (Set --seqReadCt or --rawfastq)
WARNING WARNING WARNING: Zero "usable" reads found! This could be due to a number of factors:
If the reads were not aligned via one of the standard RNA-Seq aligners such as RNA-STAR or TopHat/TopHat2, then the alignments might not use the common convention of using MAPQ to indicate multi-mapping status.
RNA-STAR and TopHat both mark multi-mapped reads by assigning them a MAPQ score of less than 255. By default QoRTs ignores these multi-mapped reads. You can deactivate this filtering step using the "--keepMultiMapped" option.
Note: Alignment via BowTie, BowTie2, or other non-spliced aligners is NOT RECOMMENDED for RNA-Seq data.
If the data was aligned using such methods, it is strongly recommended that it be realigned using a splice-aware aligner.

Continuing with output execution. Errors will likely follow...

Writing Output...
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
          java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.lang.UnsupportedOperationException: empty.max
        at scala.collection.TraversableOnce$class.max(TraversableOnce.scala:215)
        at scala.collection.AbstractTraversable.max(Traversable.scala:104)
        at qcUtils.qcInnerDistance.writeOutput(qcInnerDistance.scala:405)
        at qcUtils.runAllQC$$anonfun$runOnSeqFile$3.apply(runAllQC.scala:1410)
        at qcUtils.runAllQC$$anonfun$runOnSeqFile$3.apply(runAllQC.scala:1410)
        at scala.collection.Iterator$class.foreach(Iterator.scala:743)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1410)
        at qcUtils.runAllQC$.run(runAllQC.scala:939)
        at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:628)
        at runner.runner$.main(runner.scala:97)
        at runner.runner.main(runner.scala)
why?   thanks for an answer

**Comment by hartleys** [comment]
Sorry it took so long for me to reply, I've been pretty busy.

It looks like zero of your reads aligned uniquely.

What is this sample from? Why are there only 345 reads, all of which are
multi-mapped? How many reads did you have before alignment?
