### ISSUE TITLE
Java version for QoRTs?

### ISSUE THREAD

**Issue by ytakemon** [hartleys/QoRTs#54]
Hi @hartleys , I am trying to figure if I am running into a java version - QoRTs incompatibility here or if its an issue with my java environment in general (I typically do not work in Java so please forgive my ignorance here). I have the following java version and ran the command below:
```
[ytakemon@cadillac QoRT_install]$ java -version
java version "1.6.0_41"
Java(TM) SE Runtime Environment (build 1.6.0_41-b02)
Java HotSpot(TM) 64-Bit Server VM (build 20.14-b01, mixed mode)

[ytakemon@cadillac QoRT_install]$ java -jar QoRTs.jar --help
```
And I am getting an error regarding major.minor version support.
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: runner/runner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: runner.runner. Program will exit.
```
Any advice is appretiated.
Cheers,
Yuka

**Comment by hartleys** [comment]
Right. QoRTs requires java v1.8 or higher.

Sorry about that.

On Dec 28, 2017 3:06 PM, "Yuka Takemon" <notifications@github.com> wrote:

Hi @hartleys <https://github.com/hartleys> , I am trying to figure if I am
running into a java version - QoRTs incompatibility here or if its an issue
with my java environment in general (I typically do not work in Java so
please forgive my ignorance here). I have the following java version and
ran the command below:

[ytakemon@cadillac QoRT_install]$ java -version
java version "1.6.0_41"
Java(TM) SE Runtime Environment (build 1.6.0_41-b02)
Java HotSpot(TM) 64-Bit Server VM (build 20.14-b01, mixed mode)

[ytakemon@cadillac QoRT_install]$ java -jar QoRTs.jar --help

And I am getting an error regarding major.minor version support.

Exception in thread "main" java.lang.UnsupportedClassVersionError:
runner/runner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Could not find the main class: runner.runner. Program will exit.

Any advice is appretiated.
Cheers,
Yuka

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hartleys/QoRTs/issues/54>, or mute the thread
