### ISSUE TITLE
cannot find chromosome in genome FASTA file

### ISSUE THREAD

**Issue by AndrewLangvt** [hartleys/QoRTs#59]
I am running Qorts on BAM files generated by STAR.  It seems that Qorts is unable to locate the chromosome identified in my GTF, yet this is clearly the first chromosome listed in my genome FASTA... any thoughts?

Error output from Qorts
```
Starting QoRTs v1.2.42 (Compiled Fri Jun  2 12:23:55 EDT 2017)
Starting time: (Wed Mar 21 16:52:13 EDT 2018)
INPUT_COMMAND(QC)
  INPUT_ARG(infile)=/pylon5/mc3bg6p/al2025/isoform/STAR_analysis/STAR_mappings/1-parental/blk0-x_female_hypothalamus_m-n2_STAR2_Aligned.sortedByCoord.out.bam
  INPUT_ARG(gtffile)=/pylon5/mc3bg6p/al2025/isoform/colLiv2_genome/Rockdove_cliv2.convertedIDs.gtf
  INPUT_ARG(outdir)=/pylon5/mc3bg6p/al2025/isoform/JunctionSeq_analysis/qorts_files/rawCts/blk0-x_female_hypothalamus_m-n2
  INPUT_ARG(stranded)=true
  INPUT_ARG(maxReadLength)=Some(125)
  INPUT_ARG(genomeFA)=Some(List(/pylon5/mc3bg6p/al2025/isoform/colLiv2_genome/GCA_001887795.1_colLiv2_genomic.fna))
  INPUT_ARG(rawfastq)=Some(List(/pylon5/mc3bg6p/al2025/parental_study/trim_cor_reads/1-parental/blk0-x_female_hypothalamus_m-n2.R1.cor.fq.gz, /pylon5/mc3bg6p/al2025/parental_study/trim_cor_reads/1-parental/blk0-x_female_hypothalamus_m-n2.R2.cor.fq.gz))
  INPUT_ARG(outfilePrefix)=blk0-x_female_hypothalamus_m-n2_
Created Log File: /pylon5/mc3bg6p/al2025/isoform/JunctionSeq_analysis/qorts_files/rawCts/blk0-x_female_hypothalamus_m-n2/blk0-x_female_hypothalamus_m-n2_QC.PdGmeDHprlTW.log
Warning: run-in-progress file "/pylon5/mc3bg6p/al2025/isoform/JunctionSeq_analysis/qorts_files/rawCts/blk0-x_female_hypothalamus_m-n2/blk0-x_female_hypothalamus_m-n2_QC.QORTS_RUNNING" already exists. Is there another QoRTs job running?
Starting QC
[Time: 2018-03-21 16:52:13] [Mem usage: [75MB / 2058MB]] [Elapsed Time: 00:00:00.0000]
QoRTs is Running in paired-end mode.
QoRTs is Running in any-sorted mode.
NOTE: Function "overlapMatch" requires function "mismatchEngine". Adding "mismatchEngine" to the active function list...
Running functions: CigarOpDistribution, GCDistribution, GeneCalcs, InsertSize, 
        JunctionCalcs, NVC, QualityScoreDistribution, StrandCheck, 
        chromCounts, cigarLocusCounts, fastqUtils, mismatchEngine, 
        overlapMatch, readLengthDistro, referenceMatch, 
        writeBiotypeCounts, writeClippedNVC, writeDESeq, 
        writeDEXSeq, writeGeneBody, writeGeneCounts, 
        writeGenewiseGeneBody, writeJunctionSeqCounts, 
        writeKnownSplices, writeNovelSplices, writeSpliceExon
Checking first 10000 reads. Checking SAM file for formatting errors...
NOTE: Read length is not consistent.
   In the first 10000 reads, read length varies from 36 to 125 (param maxReadLength=125)
Note that using data that is hard-clipped prior to alignment is NOT recommended, because this makes it difficult (or impossible) to determine the sequencer read-cycle of each nucleotide base. This may obfuscate cycle-specific artifacts, trends, or errors, the
   Sorting Note: Reads are not sorted by name (This is OK).
   Sorting Note: Reads are sorted by position (This is OK).
Done checking first 10000 reads. WARNINGS FOUND!
SAMRecord Reader Generated. Read length: 125.
[Time: 2018-03-21 16:52:16] [Mem usage: [289MB / 2595MB]] [Elapsed Time: 00:00:02.0094]
..........[1000000 Read-Pairs processed] [Time: 2018-03-21 16:53:00] 
..........[2000000 Read-Pairs processed] [Time: 2018-03-21 16:53:44] 
..........[3000000 Read-Pairs processed] [Time: 2018-03-21 16:54:28] 
..........[4000000 Read-Pairs processed] [Time: 2018-03-21 16:55:13] 
..........[5000000 Read-Pairs processed] [Time: 2018-03-21 16:55:57] 
..........[6000000 Read-Pairs processed] [Time: 2018-03-21 16:56:41] 
..........[7000000 Read-Pairs processed] [Time: 2018-03-21 16:57:25] 
..........[8000000 Read-Pairs processed] [Time: 2018-03-21 16:58:09] 
..........[9000000 Read-Pairs processed] [Time: 2018-03-21 16:58:54] 
.........
Compiling flat feature annotation, internally in memory...
Internal flat feature annotation compiled!
QC Utilities Generated!
[Time: 2018-03-21 16:59:44] [Mem usage: [1466MB / 3219MB]] [Elapsed Time: 00:07:30.0833]
<====== FATAL ERROR! ======>
----------------------------
     Error message: "FATAL ERROR: Cannot find chromosome "CM007525.1" in genome FASTA file!"
     Stack Trace:
        java.lang.Thread.getStackTrace(Thread.java:1559)
        internalUtils.Reporter$.error(Reporter.scala:294)
        internalUtils.genomicAnnoUtils$EfficientGenomeSeqContainer_MFA.switchToChrom(genomicAnnoUtils.scala:169)
        internalUtils.genomicAnnoUtils$EfficientGenomeSeqContainer.shiftBufferTo(genomicAnnoUtils.scala:110)
        qcUtils.qcOverlapMatch.runOnReadPair(qcOverlapMatch.scala:218)
        qcUtils.qcOverlapMatch.runOnReadPair(qcOverlapMatch.scala:83)
        qcUtils.runAllQC$$anonfun$runOnSeqFile$2.apply(runAllQC.scala:1312)
        qcUtils.runAllQC$$anonfun$runOnSeqFile$2.apply(runAllQC.scala:1285)
        scala.collection.Iterator$class.foreach(Iterator.scala:743)
        internalUtils.stdUtils$IteratorProgressReporter$$anon$5.foreach(stdUtils.scala:487)
        qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1285)
        qcUtils.runAllQC$.run(runAllQC.scala:939)
        qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:628)
        runner.runner$.main(runner.scala:97)
        runner.runner.main(runner.scala)
<==========================>
Exception in thread "main" java.lang.Exception: FATAL ERROR: Cannot find chromosome "CM007525.1" in genome FASTA file!
        at internalUtils.Reporter$.error(Reporter.scala:299)
        at internalUtils.genomicAnnoUtils$EfficientGenomeSeqContainer_MFA.switchToChrom(genomicAnnoUtils.scala:169)
        at internalUtils.genomicAnnoUtils$EfficientGenomeSeqContainer.shiftBufferTo(genomicAnnoUtils.scala:110)
        at qcUtils.qcOverlapMatch.runOnReadPair(qcOverlapMatch.scala:218)
        at qcUtils.qcOverlapMatch.runOnReadPair(qcOverlapMatch.scala:83)
        at qcUtils.runAllQC$$anonfun$runOnSeqFile$2.apply(runAllQC.scala:1312)
        at qcUtils.runAllQC$$anonfun$runOnSeqFile$2.apply(runAllQC.scala:1285)
        at scala.collection.Iterator$class.foreach(Iterator.scala:743)
        at internalUtils.stdUtils$IteratorProgressReporter$$anon$5.foreach(stdUtils.scala:487)
        at qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1285)
        at qcUtils.runAllQC$.run(runAllQC.scala:939)
        at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:628)
        at runner.runner$.main(runner.scala:97)
        at runner.runner.main(runner.scala)
```

Genome FASTA

```
[al2025@br018 colLiv2_genome]$ head GCA_001887795.1_colLiv2_genomic.fna 
>CM007525.1 Columba livia breed Danish Tumbler chromosome 1, whole genome shotgun sequence
TGCCGGGACCCGGTGAGCTGGTGGTGCTGAGCCCCGGTGAGCTGGTGGTGCTGATCCTGGGTGTGCCGGTTGTGCCAAAC
CCTGATGCTCCGGTCGCGCCGACACTCGGTGCGGTGGTTGTGCCGGGACCCCGTGTGCCGGTTTTGCCGATCCCCGCCGT
GCCGGTGACACCGAGTCCCGTTACGCTGGTTGTGCCGATCCCCGGTGTGTACCGGTGTCGGTTGTGCTGATGCCACCGGT
GCCGGTTGTGCTGATGCCGCCGGTGCCGGTTGTGCCGATGCCGCCGGTGCCGATGCCACCGGTGTCGGTTGTGCTGATGC
CACCGGTGCCGGTTGTGCTGATGCCGCCGGTGCCGGTTGTGCCGATGCCGCCGGTGCCGATGCCACCGGTGTCGGTTGTG
CTGATGCCACCGGTGCCGGTTGTGCTGATGCCGCCGGTGCCGGTTGTGCCGATGCCGCCGGTGCCGATGCCACCGGTGTC
GGTTGTGCTGATGCCACCGGTGCCGGTTGTGCTGATGCCGCCGGTGCCGGTTGTGCCGATGCCGCCGGTGCCGATGCCAC
CGGTGTCGGTTGTGCTGATGCCACCGGTGCCGGTTGTGCTGATGCCACCGATCCCGGTGTCACCGATGCCGTTTGTGCCG
ATCTCGCCGTCCCCGATGCTGGTCGTGCCGACCCCGGTGTCCCCGCGGAAGATGCCGGTTGTGCCGATGCCACCGATCTT
```

**Comment by hartleys** [comment]
Known issue. Fasta files with additional information beyond the chromosome name can't be parsed.

I'm patching the issue now.
