### ISSUE TITLE
RuntimeIOException: java.io.FileNotFoundException: --stranded

### ISSUE THREAD

**Issue by ag009** [hartleys/QoRTs#61]
Hello,
I have a similar question to #21.
When I run the commend:
`java -jar ~/src/QoRTs.jar QC --stranded ~/01bam/OA1316.bam  ~/output/count/oa1316`

It gives me the result like this:
`Error info:
Exception in thread "main" net.sf.samtools.util.RuntimeIOException: java.io.FileNotFoundException: --stranded (No such file or directory)
        at net.sf.samtools.SAMFileReader.init(SAMFileReader.java:671)
        at net.sf.samtools.SAMFileReader.<init>(SAMFileReader.java:184)
        at net.sf.samtools.SAMFileReader.<init>(SAMFileReader.java:139)
        at qcUtils.runAllQC$.runOnSeqFile(runAllQC.scala:1012)
        at qcUtils.runAllQC$.run(runAllQC.scala:960)
        at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:672)
        at runner.runner$.main(runner.scala:97)
        at runner.runner.main(runner.scala)
Caused by: java.io.FileNotFoundException: --stranded (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at net.sf.samtools.SAMFileReader.init(SAMFileReader.java:638)
        ... 7 more`

Does that because I don't provide the gtf file?
In order words, gtf is necessary?

Thanks for your helping :)

**Comment by ag009** [comment]
After I adding the gtf file, it work!!
