### ISSUE TITLE
Exception in thread "main" java.io.FileNotFoundException:  /gpfs/ts0/projects/Research_Project-T113519/qc_collection/QoRTs_output/QC.9gZCUFz5rnuA.log (No such file or directory)

### ISSUE THREAD

**Issue by mya2152** [hartleys/QoRTs#76]
I'm trying to run some quality control on aligned RNA Sequence reads, these were aligned and merged into single files using STAR and SAMTOOLS. I've noticed the file name of QC.xxxxxxxxxxxx.log changes to random values and the program is trying to find this random file for whatever reason which of course doesn't exist.

$ java -Xmx4g -jar /gpfs/ts0/home/mya205/packages/QoRTs/qortsstable/QoRTs-STABLE.jar QC \ /gpfs/ts0/projects/Research_Project-T113519/ftp1.sequencing.exeter.ac.uk/H0243/24_rna_alignment/ftp3013_KOA_xAligned.sortedByCoord.out.bam \ /gpfs/ts0/projects/Research_Project-T113519/STAR_files/referenceGenomes/GRCh38/Homo_sapiens_GRCh38_98.gtf \ /gpfs/ts0/projects/Research_Project-T113519/qc_collection/QoRTs_output

OUTPUT:
Starting QoRTs v1.3.6 (Compiled Tue Sep 25 11:21:46 EDT 2018)
Starting time: (Mon Nov 25 10:12:03 GMT 2019)
INPUT_COMMAND(QC)
  INPUT_ARG(infile)= /gpfs/ts0/projects/Research_Project-T113519/ftp1.sequencing.exeter.ac.uk/H0243/24_rna_alignment/ftp3013_KOA_xAligned.sortedByCoord.out.bam
  INPUT_ARG(gtffile)= /gpfs/ts0/projects/Research_Project-T113519/STAR_files/referenceGenomes/GRCh38/Homo_sapiens_GRCh38_98.gtf
  INPUT_ARG(outdir)= /gpfs/ts0/projects/Research_Project-T113519/qc_collection/QoRTs_output
Creating Directory:  /gpfs/ts0/projects/Research_Project-T113519/qc_collection/QoRTs_output
============================FATAL_ERROR============================
QoRTs encountered a FATAL ERROR. For general help, use command:
          java -jar path/to/jar/QoRTs.jar --man
============================FATAL_ERROR============================
Error info:
Exception in thread "main" java.io.FileNotFoundException:  /gpfs/ts0/projects/Research_Project-T113519/qc_collection/QoRTs_output/QC.9gZCUFz5rnuA.log (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
        at java.io.FileWriter.<init>(FileWriter.java:63)
        at internalUtils.fileUtils$.openWriter(fileUtils.scala:64)
        at internalUtils.Reporter$AddedFileReportLogger.<init>(Reporter.scala:123)
        at internalUtils.Reporter$.init_completeLogFile(Reporter.scala:215)
        at qcUtils.runAllQC$.run(runAllQC.scala:748)
        at qcUtils.runAllQC$allQC_runner.run(runAllQC.scala:680)
        at runner.runner$.main(runner.scala:98)
        at runner.runner.main(runner.scala)

**Comment by mya2152** [comment]
Figured out the error, anyone else wondering, do not include any spaces after specifiying file directory with "\".
